// Command gencountries builds packed country tables from data/countries.json.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strconv"
	"strings"
)

type tzJSON struct {
	ZoneName string  `json:"ZoneName"`
	Lon      float64 `json:"Lon"`
}

type coordJSON struct {
	Lat float64 `json:"Lat"`
	Lon float64 `json:"Lon"`
}

type countryJSON struct {
	ID          uint8     `json:"id"`
	Code2       string    `json:"cc"`
	Code3       string    `json:"ccc"`
	Name        string    `json:"name"`
	Native      string    `json:"native"`
	Continent   string    `json:"continent"`
	Capital     string    `json:"capital"`
	Currency    []string  `json:"currency"`
	Languages   []string  `json:"langs"`
	Phones      []string  `json:"phones"`
	Coordinates coordJSON `json:"corrd"`
	TimeZones   []tzJSON  `json:"zones"`
}

var continentIDs = map[string]uint8{
	"EU": 1,
	"AS": 2,
	"AF": 3,
	"OC": 4,
	"SA": 5,
	"NA": 6,
	"AN": 7,
}

func main() {
	src := flag.String("src", "data/countries.json", "input JSON")
	out := flag.String("out", "country_data.go", "output Go file")
	flag.Parse()

	raw, err := os.ReadFile(*src)
	if err != nil {
		fatal(err)
	}
	var list []countryJSON
	if err := json.Unmarshal(raw, &list); err != nil {
		fatal(err)
	}
	if len(list) == 0 || len(list) > 256 {
		fatal(fmt.Errorf("unexpected country count %d", len(list)))
	}
	for i, c := range list {
		if int(c.ID) != i {
			fatal(fmt.Errorf("country ID %d at index %d, want sequential", c.ID, i))
		}
	}

	generated, err := build(*src, list)
	if err != nil {
		fatal(err)
	}
	formatted, err := format.Source(generated)
	if err != nil {
		os.Stderr.Write(generated)
		fatal(err)
	}
	if err := os.WriteFile(*out, formatted, 0644); err != nil {
		fatal(err)
	}
}

func build(srcPath string, list []countryJSON) ([]byte, error) {
	var (
		buf        bytes.Buffer
		currencies []string
		languages  []string
		phones     []string
		zones      []tzJSON
		code2AZ    [26][26]uint8
		code3AZ    [26][26][26]uint8
		special2   [][3]any
		special3   [][4]any
	)

	fmt.Fprintf(&buf, "// Code generated by internal/cmd/gencountries from %s. DO NOT EDIT.\n", srcPath)
	buf.WriteString("package gogeo\n\n")

	buf.WriteString("var countryISO2 = [...]string{\n")
	for _, c := range list {
		fmt.Fprintf(&buf, "\t%s,\n", strconv.Quote(c.Code2))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var countryISO3 = [...]string{\n")
	for _, c := range list {
		fmt.Fprintf(&buf, "\t%s,\n", strconv.Quote(c.Code3))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var countries = [...]Country{\n")
	for i, c := range list {
		if len(c.Code2) != 2 {
			return nil, fmt.Errorf("country %d: invalid code2 %q", i, c.Code2)
		}
		if len(c.Code3) != 0 && len(c.Code3) != 3 {
			return nil, fmt.Errorf("country %d: invalid code3 %q", i, c.Code3)
		}

		var code3 [3]byte
		if len(c.Code3) == 3 {
			copy(code3[:], c.Code3)
		}

		indexCode2(c.Code2, uint8(i), &code2AZ, &special2)
		if c.Code3 != "" {
			indexCode3(c.Code3, uint8(i), &code3AZ, &special3)
		}

		currOff, currN := appendPacked(&currencies, c.Currency)
		langOff, langN := appendPacked(&languages, c.Languages)
		phoneOff, phoneN := appendPacked(&phones, c.Phones)
		zoneOff, zoneN := appendZones(&zones, c.TimeZones)

		native := c.Native
		if native == c.Name {
			native = c.Name
		}

		fmt.Fprintf(&buf, "\t{ID: %d, Code2: Code2{%s}, Name: %s, Native: %s, Capital: %s, Coordinates: Coordinates{Lat: %s, Lon: %s}, continent: %d, currN: %d, langN: %d, phoneN: %d, zoneN: %d, code3: [3]byte{%s}, currOff: %d, langOff: %d, phoneOff: %d, zoneOff: %d},\n",
			c.ID,
			bytesLit([]byte(c.Code2)),
			strconv.Quote(c.Name),
			strconv.Quote(native),
			strconv.Quote(c.Capital),
			fmtFloat(c.Coordinates.Lat),
			fmtFloat(c.Coordinates.Lon),
			continentIDs[c.Continent],
			currN, langN, phoneN, zoneN,
			bytesLit(code3[:]),
			currOff, langOff, phoneOff, zoneOff,
		)
	}
	buf.WriteString("}\n\n")

	writeStringTable(&buf, "currencyTable", currencies)
	writeStringTable(&buf, "languageTable", languages)
	writeStringTable(&buf, "phoneTable", phones)

	buf.WriteString("var timezoneTable = [...]TimeZone{\n")
	for _, z := range zones {
		fmt.Fprintf(&buf, "\t{%s, %s},\n", strconv.Quote(z.ZoneName), fmtFloat(z.Lon))
	}
	buf.WriteString("}\n\n")

	writeCode2Index(&buf, code2AZ)
	writeCode3Index(&buf, code3AZ)
	writeCode2Special(&buf, special2)
	writeCode3Special(&buf, special3)
	return buf.Bytes(), nil
}

func indexCode2(code string, id uint8, az *[26][26]uint8, special *[][3]any) {
	b0, b1 := code[0], code[1]
	if isAZ(b0) && isAZ(b1) {
		az[b0-'A'][b1-'A'] = id
		return
	}
	*special = append(*special, [3]any{b0, b1, id})
}

func indexCode3(code string, id uint8, az *[26][26][26]uint8, special *[][4]any) {
	b0, b1, b2 := code[0], code[1], code[2]
	if isAZ(b0) && isAZ(b1) && isAZ(b2) {
		az[b0-'A'][b1-'A'][b2-'A'] = id
		return
	}
	*special = append(*special, [4]any{b0, b1, b2, id})
}

func isAZ(b byte) bool { return b >= 'A' && b <= 'Z' }

func appendPacked(dst *[]string, values []string) (off uint16, n uint8) {
	if len(values) == 0 {
		return 0, 0
	}
	off = uint16(len(*dst))
	*dst = append(*dst, values...)
	return off, uint8(len(values))
}

func appendZones(dst *[]tzJSON, values []tzJSON) (off uint16, n uint8) {
	if len(values) == 0 {
		return 0, 0
	}
	off = uint16(len(*dst))
	*dst = append(*dst, values...)
	return off, uint8(len(values))
}

func writeStringTable(buf *bytes.Buffer, name string, values []string) {
	fmt.Fprintf(buf, "var %s = [...]string{\n", name)
	for _, v := range values {
		fmt.Fprintf(buf, "\t%s,\n", strconv.Quote(v))
	}
	buf.WriteString("}\n\n")
}

func writeCode2Index(buf *bytes.Buffer, az [26][26]uint8) {
	buf.WriteString("var code2Index = [26][26]uint8{\n")
	for i := 0; i < 26; i++ {
		var parts []string
		for j := 0; j < 26; j++ {
			if az[i][j] == 0 {
				continue
			}
			parts = append(parts, fmt.Sprintf("%d: %d", j, az[i][j]))
		}
		if len(parts) == 0 {
			continue
		}
		fmt.Fprintf(buf, "\t%d: {%s},\n", i, strings.Join(parts, ", "))
	}
	buf.WriteString("}\n\n")
}

func writeCode3Index(buf *bytes.Buffer, az [26][26][26]uint8) {
	buf.WriteString("var code3Index = [26][26][26]uint8{\n")
	for i := 0; i < 26; i++ {
		var bParts []string
		for j := 0; j < 26; j++ {
			var cParts []string
			for k := 0; k < 26; k++ {
				if az[i][j][k] == 0 {
					continue
				}
				cParts = append(cParts, fmt.Sprintf("%d: %d", k, az[i][j][k]))
			}
			if len(cParts) == 0 {
				continue
			}
			bParts = append(bParts, fmt.Sprintf("%d: {%s}", j, strings.Join(cParts, ", ")))
		}
		if len(bParts) == 0 {
			continue
		}
		fmt.Fprintf(buf, "\t%d: {%s},\n", i, strings.Join(bParts, ", "))
	}
	buf.WriteString("}\n\n")
}

func writeCode2Special(buf *bytes.Buffer, special [][3]any) {
	buf.WriteString("func lookupCode2Special(b0, b1 byte) *Country {\n")
	buf.WriteString("\tswitch uint16(b0)<<8 | uint16(b1) {\n")
	for _, s := range special {
		b0, b1, id := s[0].(byte), s[1].(byte), s[2].(uint8)
		fmt.Fprintf(buf, "\tcase 0x%02x%02x: // %q\n\t\treturn &countries[%d]\n", b0, b1, string([]byte{b0, b1}), id)
	}
	buf.WriteString("\tdefault:\n\t\treturn &countries[0]\n\t}\n}\n\n")
}

func writeCode3Special(buf *bytes.Buffer, special [][4]any) {
	buf.WriteString("func lookupCode3Special(b0, b1, b2 byte) *Country {\n")
	buf.WriteString("\tswitch uint32(b0)<<16 | uint32(b1)<<8 | uint32(b2) {\n")
	for _, s := range special {
		b0, b1, b2, id := s[0].(byte), s[1].(byte), s[2].(byte), s[3].(uint8)
		fmt.Fprintf(buf, "\tcase 0x%02x%02x%02x: // %q\n\t\treturn &countries[%d]\n", b0, b1, b2, string([]byte{b0, b1, b2}), id)
	}
	buf.WriteString("\tdefault:\n\t\treturn &countries[0]\n\t}\n}\n")
}

func bytesLit(b []byte) string {
	parts := make([]string, len(b))
	for i, v := range b {
		parts[i] = fmt.Sprintf("0x%02x", v)
	}
	return strings.Join(parts, ", ")
}

func fmtFloat(v float64) string {
	if v == 0 {
		return "0"
	}
	return strconv.FormatFloat(v, 'g', -1, 32)
}

func fatal(err error) {
	fmt.Fprintf(os.Stderr, "gencountries: %v\n", err)
	os.Exit(1)
}
